### PR TITLE
0.4.1 - UX improvements

### PR DESCRIPTION
**Pull request by dostuffthatmatters**
- [x] #121 
- [x] #124 
- [x] #123

### CODE REVIEW

**Comment by dostuffthatmatters** [comment]
@empicano 

I have fixed the "duplicate survey" issue - hopefully :D - move "duplication" and "remove" to the config list and did a few further improvements.

What do you think?

https://commit-7f596f4---console-gz5l57j4mq-ew.a.run.app/ (uses the regular database)

**Comment by empicano** [comment]
Very nice! The "New Option" button looks much better now 😎

As only the bottom row of the card in card view is clickable now, maybe it'd be best to remove the `cursor: pointer` from the unclickable part of the card. For the TAB flow in the editor maybe it would be more intuitive to focus the newly created option field instead of the "New Option" button again.

**Comment by dostuffthatmatters** [comment]
> As only the bottom row of the card in card view is clickable now, maybe it'd be best to remove the cursor: pointer from the unclickable part of the card.

Very well noticed! I will fix that.

> For the TAB flow in the editor maybe it would be more intuitive to focus the newly created option field instead of the "New Option" button again

Yes, in the future I will do this - I didn't close #64 with this. I haven't found a pretty solution that is also simple yet - I don't want to produce a heap of garbage code there.

**Comment by empicano** [comment]
> Yes, in the future I will do this - I didn't close #64 with this. I haven't found a pretty solution that is also simple yet - I don't want to produce a heap of garbage code there.

Right, forgot there was already an issue on that, nobody likes garbage code 👍

**Pull request merged**
